//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by main.rc
//
#define IDOK3                           2
#define IDB_                            2
#define IDOK2                           3
#define IDB_ADD_FOLDER                  3
#define IDCANCEL2                       4
#define IDC_BTN_MOUNTALL                4
#define IDB_MAIN_ACTION                 4
#define IDB_REMOVE_ITEM                 4
#define IDC_BTN_UNMOUNTALL              5
#define IDB_MAIN_ACTION2                5
#define IDB_BOOT_BADPASS                5
#define IDB_REMOVE_ITEMS                5
#define IDC_BTN_ENCRYPT                 6
#define IDC_BTN_ENCRYPT_                6
#define IDB_GENERATE_KEYFILE            6
#define IDC_BTN_ENCRYPT2                7
#define IDC_BTN_DECRYPT_                7
#define IDC_BTN_ENCRYPT3                8
#define IDC_BTN_MOUNTALL_               8
#define IDC_BTN_ENCRYPT4                9
#define IDC_BTN_UNMOUNTALL_             9
#define IDD_MAIN_DLG                    101
#define IDS_STRING102                   102
#define IDC_DISKDRIVES                  104
#define IDC_DISKDRIVES_                 105
#define IDR_MENU                        106
#define IDD_DIALOG_PASS                 107
#define IDD_DIALOG_CHANGE_PASS          108
#define IDD_DIALOG1                     111
#define IDB_CHECK                       116
#define IDB_CHECK_MASK                  117
#define IDD_DIALOG_OPTIONS              118
#define DLG_CONF_GENERAL                119
#define DLG_CONF_HOTKEYS                120
#define IDI_ICON1                       121
#define IDI_ICON                        122
#define IDI_ICON_TRAY                   123
#define IDD_DIALOG_BOOT_OPTIONS         124
#define IDD_WIZARD_ENCRYPT              125
#define DLG_CONF_BOOT1                  126
#define DLG_CONF1                       127
#define DLG_WIZ_PAGE1                   128
#define DLG_WIZ_CONF                    129
#define DLG_CONF_BOOT2                  130
#define DLG_CONF2                       131
#define DLG_WIZ_PAGE2                   132
#define DLG_WIZ_LOADER                  133
#define IDB_DISK                        134
#define IDB_CDROM                       135
#define IDB_DISK_MASK                   136
#define IDB_UNDISK                      137
#define IDB_BITMAP1                     138
#define IDB_UNDISK_MASK                 139
#define IDB_DISK_MASKh                  140
#define IDB_DISK_                       140
#define IDB_DISK_h                      140
#define IDB_CDROM1                      140
#define IDB_CDROM_MASK                  140
#define DLG_MAIN_INFO                   146
#define DLG_MAIN_ACTION                 147
#define IDB_ENABLED                     152
#define DLG_WIZ_PAGE3                   153
#define DLG_WIZ_PASS                    154
#define IDR_EXEFILE2                    155
#define IDD_WIZARD_BOOT                 157
#define DLG_BOOT_PAGE2                  158
#define DLG_BOOT_CONF                   159
#define DLG_BOOT_PAGE1                  160
#define DLG_BOOT_SET                    161
#define IDR_BOOT_MENU                   162
#define DLG_BOOT_CONF_MAIN              163
#define DLG_BOOT_CONF_LOGON             164
#define DLG_BOOT_CONF_GOODPASS			165
#define DLG_BOOT_CONF_BADPASS           166
#define IDD_DIALOG_ABOUT                167
#define IDD_DIALOG_BENCHMARK            168
#define DLG_WIZ_ISO                     170
#define DLG_WIZ_FORMAT                  171
#define IDD_DIALOG_KEYFILES             172
#define DLG_WIZ_PROGRESS                173
#define DLG_BOOT_CONF_OTHER             174
#define IDR_MAIN_ACCEL                  174
#define DLG_CONF_EXTENDED               175
#define DLG_CONF_EXTNDED                175
#define DLG_WIZ_STOP					176
#define IDC_DRIVER_VER                  206
#define IDB_PREF_GENERAL                305
#define IDB_PREF_HOTKEYS                306
#define IDB_PREF_BOOT                   307
#define IDB_PREF_HOTKEYS2               308
#define IDC_KEY_UNMOUNTALL              309
#define IDC_WIPE_LOGOFF                 310
#define IDC_KEY_WIPE_                   311
#define IDC_AUTO_START                  312
#define IDC_ADV_IO_QUEUE                313
#define IDC_HIDE_FILES                  313
#define IDC_STATIC_KEY_MOUNTALL         314
#define IDC_HARD_CRYPTO_SUPPORT         314
#define IDC_STATIC_KEY_UNMOUNTALL       315
#define IDC_AUTO_MOUNT_ON_BOOT          315
#define IDC_DISABLE_TRIM                315
#define IDC_TREE                        316
#define IDC_DISABLE_TRIM2               316
#define IDC_SSD_OPTIMIZATION            316
#define IDCCANCEL                       317
#define IDC_LT_GET_PASS                 318
#define IDC_STATIC_MODE_LIST            319
#define IDC_WARNING                     320
#define IDC_COMBO_HASH3                 321
#define IDC_COMBO_MODE                  322
#define IDC_STATIC_CONF1                323
#define IDC_PAGE2                       324
#define IDC_MAIN_TAB                    325
#define IDC_COMBO_PASSES                326
#define IDE_NEW_PASS                    327
#define IDE_PASS_NEW                    327
#define IDC_STATIC_PASSES_LIST2         328
#define IDE_NEW_CONFIRM                 329
#define IDE_PASS_NEW_CONFIRM            329
#define IDC_COMBO_KBLAYOUT              330
#define IDC_COMBO_PASSES2               331
#define IDC_PAGE1                       332
#define IDC_GR_ALL                      333
#define IDC_HEAD_RATING                 334
#define IDC_HEAD_MNT_POINT              335
#define IDC_EDIT1                       1010
#define IDC_EDIT_NOTICE                 1010
#define IDC_LIST3                       1011
#define IDC_EDIT_CIPHER_INFO            1011
#define IDC_EDIT_KEY_MOUNT              1012
#define IDC_EDIT_KEY_MOUNTALL           1013
#define IDC_BUTTON1                     1014
#define IDC_BUTTON                      1015
#define IDC_EDIT_KEY_UNMOUNT            1016
#define IDC_EDIT_KEY_UNMOUNTALL         1017
#define IDC_EDIT_KEY_WIPE               1018
#define IDC_EDIT_KEY_BSOD               1019
#define IDC_PROGRESS                    1020
#define IDC_STATIC_ELAPSED              1021
#define IDC_STATIC_DONE                 1022
#define IDC_STATIC_SPEED                1023
#define IDC_STATIC_PASSWORD             1024
#define IDC_NEW_PASS                    1025
#define IDC_PASS                        1026
#define IDC_STATIC_SECTOR               1027
#define IDC_PASS2                       1027
#define IDC_MNT_POINT                   1027
#define IDC_NEW_PASS2                   1027
#define IDC_STATIC_CONFIRM              1028
#define IDC_PASS3                       1028
#define IDC_NEW_CONFIRM                 1029
#define IDC_EDIT_PASS                   1030
#define IDC_NEW_CONFIRM2                1030
#define IDC_EDIT_CONFIRM                1031
#define IDC_NEW_CONFIRM3                1031
#define IDE_PASS                        1032
#define IDC_CHECK_SHOW                  1033
#define IDC_NEW_CONFIRM4                1033
#define IDC_LIST                        1034
#define IDC_USE_KEYFILES                1034
#define IDC_EXPLORER_ON_MOUNT           1035
#define IDC_NEW_CONFIRM5                1035
#define IDC_____                        1036
#define IDC_CHECK_SHOW_CURRENT          1036
#define IDC_MSG                         1037
#define IDC_USE_KEYFILES_CURRENT        1037
#define IDC_UNMOUNT_LOGOFF              1038
#define IDC_STATIC_LIST                 1039
#define IDC_STATIC_MAIN                 1040
#define IDC_BT_CANCEL_TMOUT             1041
#define IDC_BUTTON2                     1042
#define IDC_BUTTON3                     1043
#define IDC_STATIC_PASSDLG              1044
#define IDC_STATIC_PROCESS              1045
#define IDC_BTN_MOUNT                   1046
#define IDB_MAIN_INFO                   1047
#define IDC_BTN_MOUNT2                  1048
#define IDC_BTN_INSTALL                 1048
#define IDC_CHECK1                      1049
#define IDC_CHECK2                      1050
#define IDC_CHECK3                      1051
#define IDC_CHECK4                      1053
#define IDC_TAB                         1057
#define IDC_FORCE_UNMOUNT               1058
#define IDC_CACHE_PASSWORDS             1059
#define IDC_KEY_WIPE                    1060
#define IDC_KEY_BSOD                    1061
#define IDC_OK                          1062
#define IDC_LT_DSP_PASS                 1072
#define IDC_LT_MASK_PASS                1073
#define IDC_KEY_MOUNTALL                1074
#define IDC_KEY_USEEXT                  1075
#define IDC_STATIC_KEY_MOUNT            1076
#define IDC_STATIC_KEY_UNMOUNT          1077
#define IDC_STATIC_KEY_WIPE             1078
#define IDC_STATIC_KEY_BSOD             1079
#define IDC_RADIO_ENCRYPT               1081
#define IDC_MBR_BOOT                    1081
#define IDC_NEXT                        1082
#define IDC_RADIO_REENCRYPT             1082
#define IDC_EFI_BOOT                    1082
#define IDC_BACK                        1083
#define IDC_RADIO_FORMAT                1083
#define IDC_BACK2                       1084
#define IDC_LT_MESSAGE                  1085
#define IDC_BT_LIST                     1088
#define IDC_COMBO1                      1089
#define IDC_COMBO_ALGORT                1090
#define IDC_COMBO_HASH                  1091
#define IDC_STATIC_HASH_LIST            1092
#define IDC_STATIC_ALG_LIST             1093
#define IDC_COMBO_HASH2                 1094
#define IDC_STATIC_ALG_LIST2            1096
#define IDC_STATIC_PASSES_LIST          1097
#define IDC_COMBO_MODE2                 1098
#define IDC_WIZ_CONF_WARNING            1098
#define IDC_STATIC_SELECT_PART          1099
#define IDC_HEAD_CURRENT                1100
#define IDC_HEAD_PASS                   1100
#define IDC_HEAD_NEW                    1101
#define IDC_HEAD_PASS_NEW               1101
#define IDC_HEAD_PASS2                  1101
#define IDC_HEAD_MOUNT_OPTIONS          1101
#define IDC_COMBO_BOOT_INST             1102
#define IDC_BOOT_DEVS                   1103
#define IDB_BOOT_PREF                   1104
#define IDC_PAGE3                       1105
#define IDP_BREAKABLE                   1109
#define IDC_PE_UNCRK                    1111
#define IDC_PE_HIGH                     1112
#define IDC_PE_MEDIUM                   1113
#define IDC_PE_LOW                      1114
#define IDC_PE_NONE                     1115
#define IDE_CONFIRM                     1116
#define IDC_LAUOUTS_LIST                1117
#define IDC_LAYOUTS_LIST                1117
#define IDC_GR_CAPS                     1118
#define IDE_ISO_SRC_PATH                1118
#define IDC_GR_SMALL                    1119
#define IDC_GR_DIGITS                   1120
#define IDC_GR_SPACE                    1121
#define IDC_GR_SPEC                     1122
#define IDC_PAGE4                       1123
#define IDC_ERR                         1124
#define IDC_PASS_STATUS                 1124
#define IDC_INFO_TABLE                  1125
#define IDC_INF_TABLE                   1125
#define IDC_PASS_STATUS_CURRENT         1125
#define IDC_ACT_TABLE                   1126
#define IDT_INFO                        1129
#define IDB_ACT_PAUSE                   1130
#define IDC_FRAME_RIGHT                 1133
#define IDC_FRAME_LEFT                  1134
#define IDC_FRAME_LEFT2                 1135
#define IDC_INFO_BREAK                  1136
#define IDC_COMBO_LOADER_TYPE           1140
#define IDC_WZD_BOOT_DEVS               1141
#define IDC_CHECK_CONFIG                1142
#define IDC_HEAD_BOOT_DEV               1143
#define IDC_HEAD_BOOT_FILE              1144
#define IDE_BOOT_PATH                   1145
#define IDB_BOOT_PATH                   1146
#define IDB_BOOT_MAIN                   1147
#define IDB_BOOT_LOGON                  1148
#define IDB_ISO_OPEN_DST                1148
#define IDC_BOOT_TAB                    1149
#define IDC_HEAD_BOOT_FILE2             1149
#define IDC_COMBO_METHOD                1150
#define IDC_COMBO_SHOW_PASS             1151
#define IDC_PART_LIST_BY_ID             1152
#define IDC_COMBO_AUTH_TYPE             1152
#define IDC_BT_ENTER_PASS_MSG           1154
#define IDB_BT_CONF_EMB_KEY             1156
#define IDE_RICH_BOOTMSG                1157
#define IDC_COMBO_AUTH_TMOUT            1158
#define IDC_STATIC_AUTH_TYPE            1159
#define IDC_COMBO_BAD_PASS_ACT          1160
#define IDC_CNT_BOOTMSG                 1160
#define IDE_RICH_ERRPASS_MSG            1161
#define IDC_BT_BAD_PASS_MSG             1162
#define IDC_BTN_MOUNT_                  1163
#define IDC_CNT_BOOTMSG2                1163
#define IDC_CNT_ERRMSG                  1163
#define IDC_HEAD1                       1164
#define IDC_BTN_WIZARD                  1164
#define IDC_HEAD2                       1165
#define IDC_ICON_MAIN                   1165
#define IDC_HEAD3                       1166
#define IDC_ABOUT1                      1166
#define IDC_ABOUT2                      1167
#define IDC_ABOUT3                      1168
#define IDC_ABOUT_URL1                  1168
#define IDC_ABOUT4                      1169
#define IDC_ABOUT_URL2                  1169
#define IDC_SPEED                       1170
#define IDC_DRIVES_HEAD                 1171
#define IDC_ABOUT5                      1171
#define IDC_BT_ACTION_NOPASS            1172
#define IDC_LIST_BENCHMARK              1173
#define IDB_REFRESH_TEST                1174
#define IDC_PAGE0                       1176
#define IDC_PAGE0_                      1177
#define IDC_COMBO_FS_LIST               1178
#define IDC_CHECK_QUICK_FORMAT          1179
#define IDC_HEAD                        1180
#define IDC_COMBO_MNPOINT               1181
#define IDC_CHECK_MNT_SET               1184
#define IDC_COMBO_PRF                   1185
#define IDC_CHECK_MNT_SET2              1185
#define IDC_CHECK_RO_SET                1185
#define IDC_BTN_CHANGE_CONF             1187
#define IDC_BTN_UPDATE                  1188
#define IDB_USE_KEYFILES                1189
#define IDC_LIST_KEYFILES               1190
#define IDB_USE_KEYFILES_CURRENT        1190
#define IDB_ADD_FILE                    1191
#define IDC_CHECK_SHOW_NEW              1192
#define IDC_USE_KEYFILES_NEW            1193
#define IDC_HEAD_PASS_CURRENT           1194
#define IDB_USE_KEYFILES_NEW            1195
#define IDE_PASS_CURRENT                1196
#define IDC_LINE_BOTTOM                 1197
#define IDC_STATIC_RIGHT                1198
#define IDC_PASS_STATUS_NEW             1204
#define IDC_RESIZING                    1205
#define IDC_TAB1                        1206
#define IDT_TAB                         1207
#define IDT_BOOT_TAB                    1208
#define IDE_ISO_DST_PATH                1209
#define IDB_ISO_OPEN_SRC                1210
#define IDC_STATIC_STATUS               1211
#define IDC_PROGRESS_ISO                1212
#define IDC_STATUS_PROGRESS             1213
#define IDC_ISO_PROGRESS                1214
#define IDC_USE_HARD_CRYPTO             1215
#define IDC_SET_VERBOSE                 1216
#define IDC_CONF_WARNING                1217
#define IDC_USE_SMALL_BOOT              1218
#define IDC_USE_SHIM_BOOT               1219
#define IDC_BT_GOOD_PASS_MSG            1220
#define IDE_RICH_OKPASS_MSG             1221
#define IDC_BT_AUTH_MSG                 1222
#define IDE_RICH_AUTH_MSG               1223
#define IDC_CNT_GOODMSG                 1224
#define IDC_CNT_AUTOMSG                 1225
#define IDC_BT_USE_OSK                  1226
#define IDC_COMBO_KDF                   1227
#define IDC_COMBO_KDF_CURRENT           1228
#define IDC_COMBO_KDF_NEW               1236
#define IDC_KDF_LABEL                   1229
#define IDC_KDF_LABEL_CURRENT           1230
#define IDC_CHECK_SKIP_UNUSED           1231
#define IDC_USE_KEY_SLOTS               1232
#define IDE_KEY_SLOT_INDEX              1233
#define IDC_CLEAR_KEY_SLOTS             1234
#define IDC_CHECK_USE_BACKUP            1235
#define IDC_BT_BLOCK_UNENCRYPTED        1237
#define IDC_NO_HIBERNATION              1238
#define ID_FILE_EXIT                    40001
#define ID_VOLUMES_ENCRYPT              40002
#define ID_VOLUMES_DECRYPT              40003
#define ID_VOLUMES_MOUNT                40004
#define ID_VOLUMES_UNMOUNTVOLUME        40005
#define ID_VOLUMES_BACKUPHEADER         40006
#define ID_VOLUMES_RESTOREHEADER        40007
#define ID_VOLUMES_CHANGEPASSWORD       40008
#define ID_MOUNTVOLUME_DSFGDFSG         40009
#define ID_VOLUMES_UNMOUNT              40010
#define ID_TOOLS_UNINSTALLDRIVER        40011
#define ID_TOOLS_UNINSTALL              40012
#define ID_TOOLS_DRIVER                 40013
#define ID_VOLUMES_INSTALLBOOTCODE      40014
#define ID_VOLUMES_REMMOVEBOOT          40015
#define ID_VOLUMES_INSTALLBOOT          40016
#define ID_VOLUMES_REMOVEBOOT           40017
#define ID_BOOT_INSTALL                 40018
#define ID_BOOT_REMOVE                  40019
#define ID_Menu                         40020
#define ID_VOLUMES_MOUNTALLVOLUMES      40021
#define ID_VOLUMES_UNMOUNTALLVOLUMES    40022
#define ID_EXIT                         40023
#define ID_HELP40024                    40024
#define ID_HOMEPAGE                     40025
#define ID_VOLUMES_MOUNTALL             40026
#define ID_VOLUMES_UNMOUNTALL           40027
#define ID_HELP_ABOUT                   40028
#define ID_VOLUMES_CHANGEPASS           40029
#define ID_TOOLS_CACHEPASSWORD          40030
#define ID_TOOLS_CLEARCACHE             40031
#define ID_TOOLS_SETTINGS               40032
#define ID_TOOLS_BOOTOPTIONS            40033
#define ID_BOOT_OPTIONS                 40034
#define ID_TOOLS_CRUSH                  40035
#define ID_TOOLS_0                      40036
#define ID_TOOLS_BSOD                   40037
#define ID_POPUP_SETUPBOOTLOADER        40038
#define ID_POPUP_DELETEBOOTLOADER       40039
#define ID_POPUP_UPDATEBOOTLOADER       40040
#define asf                             40041
#define Popup                           40042
#define ID_POPUP_SETUP_LOADER           40043
#define ID_POPUP_DELETE_LOADER          40044
#define ID_POPUP_UPDATE_LOADER          40045
#define ID_TOOLS_UPDATEBOOT             40046
#define ID_BOOT_UPDATE                  40047
#define ID_TOOLS_CHANGEBOOTSETTINGS     40048
#define ID_BOOT_CHANGE_CONFIG           40049
#define ID_TOOLS_INSTALLBOOT            40050
#define ID_TOOLS_UPDATEBOT              40051
#define ID_TOOLS_REMOVEBOOT             40052
#define ID_POPUP_C                      40053
#define uk                              40054
#define ID_VOLUMES_DISMOUNTALL          40057
#define ID_VOLUMES_DISMOUNT             40058
#define ID_POPUP_UPDATETOLASTVOLUMEFORMAT 40059
#define ID_VOL_UPDATETOLASTVOLUMEFORMAT 40060
#define ID_VOLUMES_UPDATE               40061
#define ID_TOOLS_DF                     40062
#define ID_TOOLS_BENCHMARK              40063
#define ID_VOLUMES_FORMATVOLUME         40064
#define ID_VOLUMES_FORMAT               40065
#define ID_VOLUMES_REENCRYPTVOLUME      40066
#define ID_VOLUMES_REENCRYPT            40067
#define ID_VOLUMES_ADDMOUNTPOINT        40068
#define ID_VOLUMES_ADDMOUNTPOINT40069   40069
#define ID_VOLUMES_DELETE_MNTPOINT      40070
#define ID_VOLUMES_ADD_MNTPOINT         40071
#define ID_TOOLS_E                      40072
#define ID_TOOLS_                       40073
#define ID_TOOLS_ENCRYPT_CD             40074
#define ID_TAB                          40075
#define ID_TAB_BACK                     40077
#define ID_SHIFT_TAB                    40077
#define ID_BOOT_ADD_BME					40078
#define ID_BOOT_DEL_BME					40079
#define ID_BOOT_REPLACE_MS				40080
#define ID_BOOT_RESTORE_MS				40081
#define ID_PROTECT_RAW					40082
#define ID_TOOLS_DRIVER_REMOVE			40083
#define ID_TOOLS_DRIVER_UPDATE			40084
#define ID_TOOLS_HEADER_CONFIG			40085
#define ID_TOOLS_HEADER_FILE			40086
#define ID_TOOLS_TPM					40087
#define ID_BLOCK_REMOVABLE				40088
#define ID_BLOCK_HDD					40089
#define ID_BLOCK_CDROM					40090
#define ID_HELP_DONATE					40091
#define ID_HELP_FORUM					40092
#define ID_TOOLS_MOK 					40093

// Wizard Keys Dialog (Header Configuration)
#define IDD_DIALOG_HEADER                 178
#define DLG_KEYS_SLOTS                  179
#define DLG_HEADER_PROPS                180
#define DLG_KEYS_SLOT_EDIT              181

// Key Slots Tab
#define IDC_KEYS_SLOT_LIST              1240
#define IDC_BTN_SET_SLOT_PASS           1241
#define IDC_BTN_TEST_SLOT_PASS          1248
#define IDC_BTN_EDIT_SLOT               1242
#define IDC_BTN_TOGGLE_SLOT             1247
#define IDC_BTN_CLEAR_SLOT              1243
#define IDC_BTN_SET_BOOT_PASS           1246

// Slot Editor View
#define IDC_EDIT_SLOT_NAME              1244
#define IDC_HEAD_SLOT_EDIT              1245

// Properties Tab
#define IDC_EDIT_DISK_ID                1250
//#define IDC_EDIT_VOLUME_GUID            1251
//#define IDC_BTN_GEN_GUID                1252
#define IDC_RADIO_V1                    1253
#define IDC_RADIO_V2                    1254
#define IDC_EDIT_SLOT_COUNT             1255
#define IDC_CHECK_EXT_HEADER            1256
#define IDT_KEYS_TAB                    1257
#define IDC_KEYS_TAB                    1258
#define IDC_BTN_APPLY                   1259
#define IDC_HEAD_VERSION                1260
#define IDC_HEAD_PROPS                  1261
#define IDC_STATIC_DISK_ID              1262
//#define IDC_STATIC_VOLUME_GUID          1263
#define IDC_STATIC_SLOT_COUNT           1264
#define IDC_STATIC_HEADER_SIZE          1265
#define IDC_STATIC_VOLUME_NOTE          1267
#define IDC_EDIT_VOLUME_NOTE            1268
#define IDC_CHECK_NO_HIBER              1308
#define IDC_HEAD_HDR_OPTIONS            1269
#define IDC_RADIO_HDR_V1                1270
#define IDC_RADIO_HDR_V2                1271
#define IDC_STATIC_HDR_SLOTS            1272
#define IDC_EDIT_HDR_SLOTS              1273
#define IDC_STATIC_HDR_SIZE             1274
#define IDC_COMBO_HDR_SIZE              1275
#define IDC_STATIC_HDR_LABEL            1276
#define IDC_EDIT_HDR_LABEL              1277
#define IDC_CHECK_BAK_HEADER            1278
#define IDC_STATIC_STORAGE_SIZE         1283
#define IDC_EDIT_STORAGE_SIZE           1284

// Layout Change Controls (Properties Tab)
#define IDC_COMBO_HDR_SIZE_PROPS        1285
#define IDC_CHECK_HDR_BACKUP            1286
#define IDC_RADIO_STORAGE_FILE          1287
#define IDC_RADIO_STORAGE_END           1288
#define IDC_BTN_CHANGE_LAYOUT           1289

// Keyfiles Dialog
#define IDC_COMBO_KEYFILE_MIX           1290
#define IDC_STATIC_KEYFILE_MIX          1291
#define IDB_ADD_VIRTUAL                 1292
#define IDB_ADD_HARDWARE                1293
#define IDR_MENU_ADD_HARDWARE           192
//#define IDD_DIALOG_VIRTUAL_KEYFILE      183
//#define IDE_VIRTUAL_KEYFILE_TEXT        1293
//#define IDE_VIRTUAL_KEYFILE_NAME        1294

// Benchmark Dialog
#define IDC_LIST_BENCHMARK_KDF          1280
#define IDC_STATIC_CIPHER_BENCH         1281
#define IDC_STATIC_KDF_BENCH            1282
#define IDB_CANCEL_TEST                 1283
#define WM_BENCHMARK_RESULT             (WM_USER + 100)

// Status Bar
#define IDC_STATUSBAR                   1295

// Tag Selection Dialog
#define DLG_SELECT_TAG                  182
#define IDC_COMBO_SELECT_TAG            1296
#define IDC_COMBO_SELECT_KDF            1297

// Cache Tag in Password Dialog
#define IDC_STATIC_CACHE_TAG            1298
#define IDE_CACHE_TAG                   1299

// Export embedded keyfile button
#define IDB_EXPORT_EMB_KEY              1300

// TPM Secret Loading (Add Virtual split button)
#define IDB_ADD_TPM_SECRET              1303
#define IDM_TPM_ADD_VIRTUAL             1304
#define IDM_TPM_NV_BACKUP               1305
#define IDM_TPM_SRK_BACKUP              1306
#define IDM_TPM_FILE_BACKUP             1307
#define IDR_MENU_ADD_VIRTUAL            185

// TPM Configuration Dialog
#define IDD_DIALOG_TPM                  186
#define IDT_TPM_TAB                     1310
#define IDC_TPM_TAB                     1311
#define IDC_TPM_ENTRY_LIST              1312
#define IDB_TPM_ADD_ENTRY               1313
#define IDB_TPM_REMOVE_ENTRY            1314
#define IDB_TPM_LOAD_TO_CACHE           1322
#define IDC_TPM_VERSION                 1315
#define IDC_TPM_VENDOR                  1316
#define IDC_TPM_LOCKOUT                 1317
#define IDR_MENU_TPM_ADD                187
#define IDM_TPM_ADD_PRIMARY_NV          40089
#define IDM_TPM_ADD_RECOVERY_NV         40090
#define IDM_TPM_ADD_RECOVERY_FILE       40091
#define IDM_TPM_ADD_BACKUP_FILE         40092

// TPM Dialog child dialogs
#define DLG_TPM_ENTRIES                 188
#define DLG_TPM_INFO                    189
#define DLG_TPM_PCRS                    190
#define IDC_TPM_PCR_LIST                1318
#define DLG_TPM_NV                      191
#define IDC_TPM_NV_LIST                 1319

// EFI Boot wizard checkboxes
#define IDC_CHECK_CREATE_ESP            1320
#define IDC_CHECK_CREATE_BME            1321

// Security options
#define IDC_SECURE_DESKTOP              1323
#define IDB_SECURE_PASS_ENTRY           1324

// Summary page controls
#define IDC_SUMMARY_HEAD                1325
#define IDC_SUMMARY_CIPHER              1326
#define IDC_SUMMARY_KDF                 1327
#define IDC_SUMMARY_WIPE                1328
#define IDC_SUMMARY_HEADER              1329
#define IDC_SUMMARY_NOTICE              1330

// Support Tab Dialog
#define DLG_CONF_SUPPORT                177

// Support Tab Controls
#define IDC_HEAD_SUPPORT                1410
#define IDE_SERIAL_KEY                  1411
#define IDB_GET_CERT                    1412
#define IDE_CERTIFICATE                 1413
#define IDC_CERT_INFO                   1414

// Wait dialog for cancellable KDF operations
#define IDD_DIALOG_WAIT                 1500
#define IDC_WAIT_TEXT                   1501
#define IDC_WAIT_CANCEL                 1502

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         40087
#define _APS_NEXT_CONTROL_VALUE         1308
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
